### ISSUE TITLE
find a procedure how to link documents in generated documentation

### ISSUE THREAD

**Issue by test-fullautomation** [test-fullautomation/robotframework-qconnect-base#22]
find a procedure how to link documents in generated documentation

**Comment by test-fullautomation** [comment]
Hi Holger,
do we have a solution for this?
Thank you,
 Thomas

**Comment by HolQue** [comment]
Prefer absolute links to server. Add only links to documents with a format, supported by server (txt, pdf, rst). Avoid html files because they are not rendered. In case of further tools like doxygen are involved, make sure not to let them generate HTML output. From doxygen it is told that also the LaTeX format is supported. Therefore this format should be preferred. Use pdflatex to convert tex files into pdf files.

For internal links please refer to https://github.com/test-fullautomation/RobotFramework_AIO/blob/develop/test/reference-package-test/ReferencePackage/ReferencePackage.pdf; section "Internal links"
